travis:
  secure:
    BINSTAR_TOKEN: RIQeQebVja1cH/GNwx90WpQwZYNvahyshk4VnqfXO1cWwuSeh8whbEfoDkRNXwEO0Gw5lBkqr8WKxK7klR7Cw3FjdCYUW731hP8IUOkS8vX/RX0XQqr8VHYDdAKYrpNBEGkxmZOC1f0+1rTM97Hw1RwtqQl5lC2jDnI8wi5p1a4F2nCXYXgE10jbP+AZgE68ROExzOHUW2HDvlcC6B8bSTPPjTibHGx0gGQn+CeLTgr1ny8vJRNJPqhs93/obC2g6gF8N81ouaJ7IUyw0Pf26FAhpS0WkTO6SBCN+R03pNJsSKRMkEZcs9YAialXjFVut2TYVOKoNRAHWLe4PduJ70fI5w5jPlp1V4OqZh+8Ak2NA6uXGX5dCg8wMW8cGpvb/g1/Rkl2lnvNW5iQhJBGPe7YCFif/2xOhtwAC1Jzqi1bOKRzeq5HG7H+sJvo6TNati/0YiAsPChN1dsmYXihFS1ZBHVRmrBvGxNaar8TD96a5fGvfflHnHCCUXb+H+9V4zP8j1rfhxHL0FPt4wl1BYVWfTZJISC53v5VBwl6DMmQKgUTQzHLQpASCRWzCWGJZiVxHreuHdVjhDIgvXk9Uo/DDd9+PTUBOiCbSJrxvUW1/Y2vkwvIEjDwMeRLhgizRGpl4dw9RrnOmdHfCZwlWOym6cKz/szml+2z8dS7NLw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
